version: "3.7"
services:
    web:
        # only for m1 chip
        platform: linux/x86_64
        build:
          context: api/
          dockerfile: Dockerfile 
        ports:
            - "8000:5000"
        volumes:
           - ./api/:/rpserver
        restart: always
    ws:
      build:
        context: coordinates/
        dockerfile: Dockerfile 
      restart: always
      volumes:
        - ./coordinates/:/coordinates
      ports:
        - "9999:9999"
      command: "./start.sh"

    db:
        image: "postgres:14.0"
        ports:
            - "6432:5432"
        env_file:
            - api/.env.local
        volumes:
            - pgdata:/var/lib/postgresql/data
    nginx:
        container_name: nginx
        image: nginx
        build:
          context: client/client_js/
          dockerfile: Dockerfile
        restart: always
        volumes:
          - ./client/client_js/:/usr/share/nginx/html
        ports:
          - "8080:80"
volumes:
    pgdata:
