"""empty message

Revision ID: 22e192d7a290
Revises: 
Create Date: 2020-07-13 17:17:55.446770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e192d7a290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('spot_id', name=op.f('pk__spots'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('login_email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('event', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__users'))
    )
    op.create_table('coordinates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__coordinates__user_id__users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__coordinates'))
    )
    op.create_table('event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.spot_id'], name=op.f('fk__events__spot_id__spots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__events__user_id__users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__events'))
    )
    op.create_table('users_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['users.user_id'], name=op.f('fk__users_relations__relation_id__users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__users_relations__user_id__users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__users_relations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_relations')
    op.drop_table('event')
    op.drop_table('coordinates')
    op.drop_table('users')
    op.drop_table('spots')
    # ### end Alembic commands ###
