"""empty message

Revision ID: 257ef9a6696e
Revises: 62f299aa9238
Create Date: 2020-04-23 15:27:41.878717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257ef9a6696e'
down_revision = '62f299aa9238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider', 'hometown')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rider', sa.Column('hometown', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
