"""New coordinates

Revision ID: 317aeb96b136
Revises: 4f8de84d8214
Create Date: 2020-05-05 17:37:42.763149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317aeb96b136'
down_revision = '4f8de84d8214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rider', sa.Column('friends_id', sa.String(), nullable=True))
    op.add_column('rider', sa.Column('friendship_request', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider', 'friendship_request')
    op.drop_column('rider', 'friends_id')
    # ### end Alembic commands ###
