"""New coordinates

Revision ID: 4f8de84d8214
Revises: 19867f3c826e
Create Date: 2020-05-05 16:19:06.292944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8de84d8214'
down_revision = '19867f3c826e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coordinate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rider_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coordinate_pkey'),
    sa.UniqueConstraint('rider_name', name='coordinate_rider_name_key')
    )
    op.drop_table('coordinates')
    # ### end Alembic commands ###
