"""NEw table

Revision ID: 6e1fbc54871f
Revises: 9772a8df78a8
Create Date: 2020-04-14 15:36:50.644655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1fbc54871f'
down_revision = '9772a8df78a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinate', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coordinate', 'rider', ['rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coordinate', type_='foreignkey')
    op.drop_column('coordinate', 'rider_id')
    # ### end Alembic commands ###
