"""New model

Revision ID: 899d8fcc566c
Revises: 
Create Date: 2020-04-11 15:47:11.832519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899d8fcc566c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('login_email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('hometown', sa.String(length=100), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_email'),
    sa.UniqueConstraint('profile_image')
    )
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('profile_image', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('notes'),
    sa.UniqueConstraint('profile_image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot')
    op.drop_table('rider')
    # ### end Alembic commands ###
