"""New table coordinate

Revision ID: 9772a8df78a8
Revises: 899d8fcc566c
Create Date: 2020-04-13 15:56:06.458599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9772a8df78a8'
down_revision = '899d8fcc566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinate')
    # ### end Alembic commands ###
