"""First

Revision ID: 9685924cec6c
Revises: 
Create Date: 2020-10-30 09:32:16.858215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9685924cec6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=50), nullable=False),
    sa.Column('profile_image_url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('spot_id', name=op.f('pk__spot'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50)),
    sa.Column('login_email', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date()),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=50)),
    sa.Column('profile_image_url', sa.String(length=50)),
    sa.Column('hometown', sa.String(length=50)),
    sa.Column('registration_date', sa.Date()),
    sa.Column('event', sa.Boolean()),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__user'))
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.spot_id'], name=op.f('fk__event__spot_id__spot')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__event__user_id__user')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk__event'))
    )
    op.create_table('logout_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__logout_token__user_id__user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__logout_token')),
    sa.UniqueConstraint('token', name=op.f('uq__logout_token__token'))
    )
    op.create_table('user_relations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['user.user_id'], name=op.f('fk__user_relations__related_user_id__user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__user_relations__user_id__user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__user_relations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relations')
    op.drop_table('logout_token')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('spot')
    # ### end Alembic commands ###
