version: "3.2"
services:
    web:
        build: .
        ports:
            - "8000:5000"
        volumes:
           - .:/rpserver
        restart: always
    db:
        image: "postgres:14.0"
        ports:
            - "6432:5432"
        env_file:
            - env
