version: "3.7"
services:
    web:
        # only for m1 chip
        platform: linux/x86_64
        build: .
        ports:
            - "8000:5000"
        volumes:
           - .:/rpserver
        restart: always
    db:
        image: "postgres:14.0"
        ports:
            - "6432:5432"
        env_file:
            - .env.local
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
